# Generated by Django 2.0.1 on 2018-04-01 16:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20180401_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qtable',
            name='Q_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None), blank=True, default=[[0.0, 0.0, 0.0], [0.0, 0.0, 0.0], [0.0, 0.0, 0.0], [0.0, 0.0, 0.0], [0.0, 0.0, 0.0], [0.0, 0.0, 0.0], [0.0, 0.0, 0.0], [0.0, 0.0, 0.0], [0.0, 0.0, 0.0]], null=True, size=None),
        ),
        migrations.AlterField(
            model_name='qtable',
            name='R_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None), blank=True, default=[[0.0, 0, 100.0], [100.0, 0.0, 0.0], [0.0, 100.0, 0.0], [0.0, 0, 100.0], [100.0, 0.0, 0.0], [0.0, 100.0, 0.0], [0.0, 0, 100.0], [100.0, 0.0, 0.0], [0.0, 100.0, 0.0]], null=True, size=None),
        ),
    ]
