# Generated by Django 2.0.1 on 2018-04-13 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_qtablelocal'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QTable',
            new_name='QTableGlobal',
        ),
    ]
