# Generated by Django 2.0.1 on 2018-04-14 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0010_auto_20180413_2224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Populations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store1', models.CharField(blank=True, max_length=100, null=True)),
                ('store2', models.CharField(blank=True, max_length=100, null=True)),
                ('store3', models.CharField(blank=True, max_length=100, null=True)),
                ('store4', models.CharField(blank=True, max_length=100, null=True)),
                ('chromosome1', models.CharField(blank=True, max_length=10, null=True)),
                ('chromosome2', models.CharField(blank=True, max_length=10, null=True)),
                ('chromosome3', models.CharField(blank=True, max_length=10, null=True)),
                ('chromosome4', models.CharField(blank=True, max_length=10, null=True)),
                ('store1_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store1_obj', to='mainapp.Store')),
                ('store2_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store2_obj', to='mainapp.Store')),
                ('store3_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store3_obj', to='mainapp.Store')),
                ('store4_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store4_obj', to='mainapp.Store')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
