# Generated by Django 2.0.1 on 2018-04-14 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_populations'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
