# Generated by Django 2.0.1 on 2018-04-20 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_store_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anonymous_Populations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('chromosome1', models.CharField(blank=True, max_length=10, null=True)),
                ('chromosome2', models.CharField(blank=True, max_length=10, null=True)),
                ('chromosome3', models.CharField(blank=True, max_length=10, null=True)),
                ('chromosome4', models.CharField(blank=True, max_length=10, null=True)),
                ('store1_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Astore1_obj', to='mainapp.Store')),
                ('store2_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Astore2_obj', to='mainapp.Store')),
                ('store3_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Astore3_obj', to='mainapp.Store')),
                ('store4_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Astore4_obj', to='mainapp.Store')),
            ],
        ),
        migrations.RemoveField(
            model_name='populations',
            name='store1',
        ),
        migrations.RemoveField(
            model_name='populations',
            name='store2',
        ),
        migrations.RemoveField(
            model_name='populations',
            name='store3',
        ),
        migrations.RemoveField(
            model_name='populations',
            name='store4',
        ),
    ]
