# Generated by Django 2.0.1 on 2018-04-22 10:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_auto_20180420_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qtablelocal',
            name='Q_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='qtablelocal',
            name='R_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None), blank=True, null=True, size=None),
        ),
    ]
